repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: mixed-line-ending # or whatever the name; you're the boss
        args: ["--fix", "lf"]
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 25.1.0 # https://github.com/psf/black/tags
    hooks:
      - id: black
        args: ["--config", ".black"]
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
