ARG STREAM_BASE_IMAGE
ARG STREAM_BASE_TAG

FROM ${STREAM_BASE_IMAGE}:${STREAM_BASE_TAG}

COPY scripts scripts

RUN set -xe; \
    cd scripts; \
    cp -v -p ./spixconv/ioc/autosave/* $(TOP)/autosave; \
    cp -v -p ./spixconv/ioc/db/*       $(TOP)/db; \
    cp -v -p ./spixconv/ioc/protocol/* $(TOP)/protocol; \
    cp -v -p ./spixconv/ioc/cmd/*      $(TOP)/iocBoot/iocStreamDeviceIOC;

CMD ["/bin/bash", "-c", "set -e; cd scripts/; make run-spixconv"]
