version: '3.7'
services:
    epics:
        image: lnlscon/epics-r3.15.6:v1.2
        build: 
            dockerfile: 'Dockerfile.EPICS'
            context: .
            labels:
                - "br.com.lnls-sirius.description=EPICS 3.15.6 + Modules and Python 3.7.5"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
    agilent4uhv:
        #image: lnlscon/streamdevice-ioc:Agilent4UHV-v1.1-Devel
        image: lnlscon/streamdevice-ioc:Agilent4UHV-v1.1.3-Devel
        build:
            dockerfile: 'Dockerfile'
            context: .
            labels:
                - "br.com.lnls-sirius.description=StreamDevice IOC"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
        environment:
            - "EPICS_IOC_LOG_INET=10.0.38.59"
            - "EPICS_IOC_LOG_PORT=7011"
        command: /bin/bash ./bin/agilent.sh
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

    countingPRU:
        image: lnlscon/streamdevice-ioc:CountingPRU-v1.4
        build:
            dockerfile: 'Dockerfile'
            context: .
            labels:
                - "br.com.lnls-sirius.description=StreamDevice IOC"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
        command: /bin/bash ./bin/countingPRU.sh
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"
    mbtemp:
        image: lnlscon/streamdevice-ioc:MBTemp-v1.2
        build:
            dockerfile: 'Dockerfile'
            context: .
            labels:
                - "br.com.lnls-sirius.description=StreamDevice IOC"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
        environment:
                - "EPICS_IOC_CAPUTLOG_INET=10.128.255.4"
                - "EPICS_IOC_CAPUTLOG_PORT=7012"
                - "EPICS_IOC_LOG_INET=10.128.255.4"
                - "EPICS_IOC_LOG_PORT=7011"
        command: /bin/bash ./bin/mbtemp.sh
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"
    mks937b:
        image: lnlscon/streamdevice-ioc:MKS937b-v1.7
        build:
            dockerfile: 'Dockerfile'
            context: .
            labels:
                - "br.com.lnls-sirius.description=StreamDevice IOC"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
        command: /bin/bash ./bin/mks937b.sh
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"
            - "/var/tmp/auto:/opt/epics-R3.15.6/modules/StreamDevice-2.8.9/autosave:rw"
    rackMonitoring:
        image: lnlscon/streamdevice-ioc:RackMonitoring-v1.2
        build:
            dockerfile: 'Dockerfile'
            context: .
            labels:
                - "br.com.lnls-sirius.description=StreamDevice IOC"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
        environment:
                - "EPICS_IOC_CAPUTLOG_INET=10.128.255.4"
                - "EPICS_IOC_CAPUTLOG_PORT=7012"
                - "EPICS_IOC_LOG_INET=10.128.255.4"
                - "EPICS_IOC_LOG_PORT=7011"
        command: /bin/bash ./bin/rackMonitoring.sh
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"
    spixconv:
        image: lnlscon/streamdevice-ioc:SPIxCONV-v1.6
        build:
            dockerfile: 'Dockerfile'
            context: .
            labels:
                - "br.com.lnls-sirius.description=StreamDevice IOC"
                - "br.com.lnls-sirius.department=CONS"
                - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
        command: /bin/bash ./bin/spixconv.sh
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

