ARG STREAM_BASE_IMAGE
ARG STREAM_BASE_TAG

FROM ${STREAM_BASE_IMAGE}:${STREAM_BASE_TAG}

# Install python3.9
RUN set -x; \
    apt install -y \
        build-essential \
        libbz2-dev \
        libc6-dev \
        libffi-dev \
        libgdbm-dev \
        libncursesw5-dev \
        libreadline-gplv2-dev \
        libsqlite3-dev \
        libssl-dev \
        tk-dev \
        wget \
        zlib1g-dev &&\
    rm -rf /var/lib/apt/lists/*  && \
    cd /opt && wget https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tgz && \
    tar xzf Python-3.9.4.tgz && rm -v Python-3.9.4.tgz && cd Python-3.9.4 && \
    ./configure --enable-optimizations && make -j$(nproc) altinstall

ENV PYTHON /usr/local/bin/python3.9
ENV PIP /usr/local/bin/pip3.9

RUN ${PIP} install pandas openpyxl

COPY scripts scripts

CMD ["/bin/bash", "-c", "set -e; cd scripts/; make build-mbtemp; make deploy-mbtemp; make run-mbtemp"]
