# Author: Cláudio Ferreira Carneiro
# LNLS - Brazilian Synchrotron Light Source Laboratory

FROM  ubuntu:18.04
LABEL maintainer="Claudio Carneiro <claudio.carneiro@lnls.br>"

RUN apt-get update
RUN apt-get install -y              \
        telnet                      \
        logrotate                   \
        build-essential             \
        vim                         \
        libpcre3-dev                \
        wget                        \
        git                         \
        procserv                    \
        libreadline-gplv2-dev       

# IOC operation variables
ENV EPICS_VERSION R3.15.5
ENV ARCH linux-x86_64
ENV EPICS_HOST_ARCH linux-x86_64
ENV EPICS_BASE /opt/epics-${EPICS_VERSION}/base
ENV EPICS_MODULES /opt/epics-${EPICS_VERSION}/modules

ENV ASYN /opt/epics-${EPICS_VERSION}/modules/asyn4-35
ENV CALC /opt/epics-${EPICS_VERSION}/modules/synApps/calc-R3-7-1
ENV AUTOSAVE /opt/epics-${EPICS_VERSION}/modules/autosave-R5-8
ENV PATH ${EPICS_BASE}/bin/${ARCH}:/opt/procServ:${PATH}
ENV EPICS_CA_AUTO_ADDR_LIST YES

# set correct timezone
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Pyepics libca location
ENV PYEPICS_LIBCA ${EPICS_BASE}/lib/${ARCH}/libca.so

RUN mkdir -p /opt/epics-${EPICS_VERSION}

RUN wget -O /opt/epics-R3.15.5/base-3.15.5.tar.gz   \
    https://epics.anl.gov/download/base/base-3.15.5.tar.gz

WORKDIR /opt/epics-${EPICS_VERSION}


# Epics Base
RUN cd /opt/epics-R3.15.5           &&\
    tar -xvzf base-3.15.5.tar.gz    &&\
    rm base-3.15.5.tar.gz           &&\
    mv base-3.15.5 base             &&\
    cd base                         &&\
    make

# asynDriver
RUN cd ${EPICS_BASE}                &&\
    cd ..                           &&\
    mkdir modules                   &&\
    cd modules                      &&\
    wget https://www.aps.anl.gov/epics/download/modules/asyn4-35.tar.gz                     &&\
    tar -xvzf asyn4-35.tar.gz                                                               &&\
    rm asyn4-35.tar.gz                                                                      &&\
    sed -i -e '3,4s/^/#/' -e '8s/^/#/' -e '11s/^/#/' -e '14cEPICS_BASE='${EPICS_BASE} asyn4-35/configure/RELEASE &&\
    cat  asyn4-35/configure/RELEASE                                                         &&\
    cd asyn4-35                                                                             &&\
    make

# synApps Calc Module
RUN cd ${EPICS_BASE}/../modules                                                                                     &&\
    mkdir synApps                                                                                                   &&\
    cd synApps                                                                                                      &&\
    wget https://github.com/epics-modules/calc/archive/R3-7-1.tar.gz                                                &&\
    tar -xvzf R3-7-1.tar.gz                                                                                         &&\
    rm R3-7-1.tar.gz                                                                                                &&\
    sed -i -e '5s/^/#/' -e '7,8s/^/#/' -e '13s/^/#/' -e '20cEPICS_BASE='${EPICS_BASE} calc-R3-7-1/configure/RELEASE &&\
    cd calc-R3-7-1                                                                                                  &&\
    make

# Autosave
RUN wget -O /opt/epics-R3.15.5/modules/R5-8.tar.gz   \
    https://github.com/epics-modules/autosave/archive/R5-8.tar.gz
RUN cd /opt/epics-R3.15.5/modules/      &&\
    tar -zxvf R5-8.tar.gz               &&\
    rm R5-8.tar.gz                      &&\
    cd autosave-R5-8                    &&\
    sed -i -e '8s/^/#/' -e '8iEPICS_BASE='${EPICS_BASE} configure/RELEASE &&\
    make

# Streamdevice
RUN cd ${EPICS_MODULES}                                                                         &&\
    mkdir StreamDevice-2.8.8                                                                    &&\
    cd StreamDevice-2.8.8                                                                       &&\
    mkdir autosave  && chmod -R 777 autosave                                                    &&\
    echo '' | USER=root makeBaseApp.pl -t support && echo ''                                    &&\
    wget https://github.com/paulscherrerinstitute/StreamDevice/archive/2.8.8.tar.gz             &&\
    tar -xvzf 2.8.8.tar.gz                                                                      &&\
    mv StreamDevice-2.8.8 StreamDevice_2_8_8                                                    &&\
    rm 2.8.8.tar.gz                                                                             &&\
    sed -i -e '28iASYN='${ASYN}         configure/RELEASE                                       &&\
    sed -i -e '29iCALC='${CALC}         configure/RELEASE                                       &&\
    sed -i -e '30iAUTOSAVE='${AUTOSAVE} configure/RELEASE                                       &&\
    echo 'PCRE_INCLUDE=/usr/include' > configure/RELEASE.Common.linux-x86_64                    &&\
    echo 'PCRE_LIB=/usr/lib/x86_64-linux-gnu' >> configure/RELEASE.Common.linux-x86_64                     &&\
    sed -i -e '29iPROD_LIBS += autosave'            StreamDevice_2_8_8/streamApp/Makefile                  &&\
    sed -i -e '29istreamApp_DBD += asSupport.dbd'   StreamDevice_2_8_8/streamApp/Makefile                  &&\
    sed -i -e '20istreamApp_DBD += system.dbd'      StreamDevice_2_8_8/streamApp/Makefile                  &&\
    sed -i -e '3iinclude "asSupport.dbd"'           StreamDevice_2_8_8/streamApp/streamAppInclude-3-13.dbd &&\
    rm StreamDevice_2_8_8/GNUmakefile                                                           &&\
    sed -i -e '11iDIRS += StreamDevice_2_8_8' Makefile                                          &&\
    make                                                                                        &&\
    mkdir protocol && mkdir database && mkdir iocBoot && mkdir interface

CMD tail -f /dev/null
