version: '3.7'
services:
    epics:
        image: lnlscon/epics-r3.15.8:v1.1
        build:
            dockerfile: 'Dockerfile.EPICS'
            context: .
    stream:
        image: lnlscon/streamdevice-ioc:stream
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: stream

    agilent4uhv:
        image: lnlscon/streamdevice-ioc:Agilent4UHV-v2.0
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: agilent4uhv
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

    countingPRU:
        image: lnlscon/streamdevice-ioc:CountingPRU-v2.0
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: countingPRU
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

    mbtemp:
        image: lnlscon/streamdevice-ioc:MBTemp-v1.2
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: mbtemp
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

    mks937b:
        image: lnlscon/streamdevice-ioc:MKS937b-v2.0
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: mks937b
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"
            - "/var/tmp/auto:/opt/epics-R3.15.6/modules/StreamDevice-2.8.9/autosave:rw"

    rackMonitoring:
        image: lnlscon/streamdevice-ioc:RackMonitoring-v1.2
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: rackMonitoring
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

    spixconv:
        image: lnlscon/streamdevice-ioc:SPIxCONV-v1.6
        build:
            dockerfile: 'Dockerfile'
            context: .
            target: spixconv
        volumes:
            - "./spreadsheet:/opt/streamdevice-ioc/spreadsheet:ro"

