services:
  base:
    image: streamdevice-ioc-base-image
    build:
      context: ioc/
      dockerfile: ../docker/Dockerfile
      target: static-link
      labels:
        org.opencontainers.image.source: https://github.com/lnls-sirius/streamdevice-ioc
      args:
        REPONAME: streamdevice-ioc
        RUNDIR: /opt/streamdevice-ioc
        ENTRYPOINT: /bin/bash
        RUNTIME_PACKAGES: make

  stream:
    image: ${STREAM_BASE_IMAGE}:${STREAM_BASE_TAG}
    build:
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.source: https://github.com/lnls-sirius/streamdevice-ioc
