# Author: Cláudio Ferreira Carneiro
# LNLS - Brazilian Synchrotron Light Source Laboratory
ARG EPICS_BASE_IMAGE
ARG EPICS_BASE_TAG

FROM  ${EPICS_BASE_IMAGE}:${EPICS_BASE_TAG} as stream
LABEL "maintainer"="Claudio Carneiro <claudio.carneiro@lnls.br>"
LABEL "repository"="https://github.com/lnls-sirius/streamdevice-ioc"
LABEL "br.com.lnls-sirius.description"="StreamDevice IOC"
LABEL "br.com.lnls-sirius.department"="CONS"
LABEL "br.com.lnls-sirius.maintener"="Claudio Ferreira Carneiro"

# Python3
RUN pip3 install pandas==0.23.4 xlrd==1.2.0

# VIM
RUN apt-get -y update && apt-get -y install procps vim socat

# Epics auto addr list
ENV EPICS_CA_AUTO_ADDR_LIST YES

# Base procServ port
ENV EPICS_IOC_CAPUTLOG_INET 0.0.0.0
ENV EPICS_IOC_CAPUTLOG_PORT 7012

ENV EPICS_IOC_LOG_INET 0.0.0.0
ENV EPICS_IOC_LOG_PORT 7011

ENV TOP /opt/streamdevice-ioc

RUN \
    mkdir -p ${TOP}/autosave/save &&\
    mkdir -p ${TOP}/log &&\
    mkdir -p ${TOP}/protocol &&\
    mkdir -p ${TOP}/sockets &&\
    mkdir -p ${TOP}/streamdevice-ioc-history

WORKDIR ${TOP}

COPY crontab            /etc/crontab
COPY logrotate.conf     /etc/logrotate.conf
RUN  chmod 644          /etc/logrotate.conf

COPY streamDeviceIOCApp streamDeviceIOCApp
COPY Makefile           Makefile
COPY configure          configure
COPY iocBoot            iocBoot
COPY procCtrl           /opt/procCtrl

RUN cd /opt/procCtrl && envsubst < configure/RELEASE.tmplt > configure/RELEASE &&\
    cat configure/RELEASE && make distclean && make clean && make -j$(nproc) &&\
    \
    cd ${TOP} && envsubst < configure/RELEASE.tmplt > configure/RELEASE && \
    make distclean && make clean && make -j$(nproc)

COPY scripts            scripts

CMD echo "Overwrite the command!" && ls -la ./scripts && tail -f /dev/null
