#!/bin/bash
run(){
  echo "Init IOCs"
  run_ioc ${1};
  tail -f /dev/null
}

run_ioc(){
    set +x
    # Params:
    # :1 : CMD_KEY
    echo ""
    echo "###############################################################################"
    echo "# ProcServ. Use \"socat - UNIX-CLIENT:<socket>\""
    for filename in $(ls ${TOP}/iocBoot/iocStreamDeviceIOC | sort  | grep -P "^${1}[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:?[0-9]{0,5}\.cmd$"); do
        ip=$(echo $filename | sed -e "s/${1}//" -e "s/\.cmd//")
        if [[ ${ip} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$ ]]; then
            logFile=${TOP}/log/${filename}
            iocName="$(echo ${filename} | sed  -e "s/\./_/g" -e "s/:/_/g" -e "s/_cmd//g")"
            socket_name="${TOP}/sockets/${iocName}.sock"
            set -x
            procServ \
                --name ${iocName}\
                --quiet\
                --killsig 9\
                --logfile ${TOP}/log/${filename}\
                --chdir ${TOP}/iocBoot/iocStreamDeviceIOC\
                unix:${socket_name}\
                ${TOP}/iocBoot/iocStreamDeviceIOC/${filename}
            set +x
            echo "# IOC: ${filename}    log_file: ${logFile}    unix_socket: ${socket_name}"
        fi
    done
    echo "###############################################################################"
}
