#!/bin/bash
run(){
  echo "Init cron"
  cron
  echo "Init IOCs"
  run_ioc ${1};
  tail -f /dev/null
}

run_ioc(){
    set +x
    # Check if procServControl
    if [ -f "${TOP}/procCtrl/iocBoot/iocprocCtrl/st.cmd" ]; then
        echo "###############################################################################"
        echo "# Init ProcServControl"
        set -x
        procServ \
            -n ProcCtrl \
            -q \
            --killsig 9 \
            -L /opt/streamdevice-ioc/log/procCtrl.log \
            --chdir ${TOP}/procCtrl/iocBoot/iocprocCtrl \
            unix:/opt/streamdevice-ioc/sockets/procCtrl.sock \
            ${TOP}/procCtrl/iocBoot/iocprocCtrl/st.cmd \
            TOP=${TOP}/procCtrl
        set +x
        echo "###############################################################################"
    fi

    # Params:
    # :1 : CMD_KEY
    echo ""
    echo "###############################################################################"
    echo "# ProcServ. Use \"socat - UNIX-CLIENT:<socket>\""
    for filename in $(ls ${TOP}/iocBoot/iocStreamDeviceIOC | sort  | grep -P "^${1}[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:?[0-9]{0,5}\.cmd$"); do
        ip=$(echo $filename | sed -e "s/${1}//" -e "s/\.cmd//")
        if [[ ${ip} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$ ]]; then
            logFile=${TOP}/log/${filename}
            iocName="$(echo ${filename} | sed  -e "s/\./_/g" -e "s/:/_/g" -e "s/_cmd//g")"
            socket_name="${TOP}/sockets/${iocName}.sock"
            set -x
            procServ -n ${iocName} -q --killsig 9 -L ${TOP}/log/${filename} --chdir ${TOP}/iocBoot/iocStreamDeviceIOC unix:${socket_name} ${TOP}/iocBoot/iocStreamDeviceIOC/${filename}
            set +x
            echo "# IOC: ${filename}    log_file: ${logFile}    unix_socket: ${socket_name}"
        fi
    done
    echo "###############################################################################"
}
