#!/bin/bash
clear_stream_ioc(){
    echo clear stream ioc $1
    # Clear stram-ioc folder
    pushd ${TOP}/iocBoot
        for filename in *.cmd; do
            if [[ ${filename} =~ $1(.*).cmd ]]; then
                rm ${filename}
                echo Removed old content: ${filename}
            fi
        done
    popd
}

run_ioc_unix_bridge(){
    # Params:
    # :1 : CMD_KEY
    ADDR_LIST=
    SOCKET_PATH_LIST=
    set -x
    echo UNIX Bind and .cmd configuration
    for filename in $(ls ${TOP}/iocBoot | grep -P "^${1}[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}\.cmd$"); do
            ip=$(echo $filename | sed -e "s/${1}//" -e "s/\.cmd//")

            if [[ ${ip} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$ ]]; then
                    socket_dir="/var/tmp/$filename"
                    socket_dir_skp=$(echo unix://${socket_dir} | sed 's/\//\\\//g')

                    ADDR_LIST="${ADDR_LIST} ${ip}"
                    SOCKET_PATH_LIST="${SOCKET_PATH_LIST} ${socket_dir}"

                    echo $(date)" Configuring ${TOP}/iocBoot/${filename} to use socket ${socket_dir}."
                    sed -i -r "s/drvAsynIPPortConfigure\s*\(\"[^)]+?\s*\)/drvAsynIPPortConfigure\(\"IPPort0\",\"${socket_dir_skp}\"\)/g" ${TOP}/iocBoot/${filename}
            fi
    done
    
    ./common/tcpUnix.py --socket-path-list ${SOCKET_PATH_LIST} --address-list ${ADDR_LIST} --reconnect-interval 30 &
    sleep 25

    echo
    procServPort=${BASE_PROCSERV_PORT}
    for filename in $(ls ${TOP}/iocBoot | grep -P "^${1}[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}\.cmd$"); do
        procServPort=$((procServPort + 1))
        export BASE_PROCSERV_PORT=${procServPort}
        procServ --chdir ${TOP}/iocBoot ${procServPort} ${TOP}/iocBoot/${filename}
    done
    set +x
}

run_ioc(){
    # Params:
    # :1 : CMD_KEY
    # @todo: Make this thing clear !!
    echo
    echo
    procServPort=${BASE_PROCSERV_PORT}
    for filename in $(ls ${TOP}/iocBoot | grep -P "^${1}[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:?[0-9]{0,5}\.cmd$"); do
        ip=$(echo $filename | sed -e "s/${1}//" -e "s/\.cmd//")
        if [[ ${ip} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5}$ ]]; then
                procServPort=$((procServPort + 1))
                echo $(date)' Init procServ. Command: procServ --chdir '${TOP}/iocBoot ${procServPort} ${TOP}/iocBoot/${filename}
                procServ --chdir ${TOP}/iocBoot ${procServPort} ${TOP}/iocBoot/${filename}
        fi
    done
    export BASE_PROCSERV_PORT=${procServPort}
}

copy_to_stream_device(){
    # Params:
    # :1 : CMD_KEY
    # :2 : TOP
    # Clear stream-ioc folder
    echo "Copy Stream Device"
    clear_stream_ioc $1

    PROTOCOL="protocol"
    IOC_BOOT="iocBoot"
    DB="database"

    chmod -R 777 server/cmd/

    cp -R server/db/. ${2}/${DB}/
    cp -R server/protocol/. ${2}/${PROTOCOL}/
    cp -R server/cmd/. ${2}/${IOC_BOOT}/
}

build(){
    # Params:
    # :1 : Folder
    # :2 : CMD_KEY
    # :3 : Base Epics CA Port

    # Clear the /cmd folder
    rm ${1}/server/cmd/*

    pushd $1
        ./generate.py --cmd-prefix ${2} --top ${TOP} ${EPICS_CA_PORT_INCREASE} ${BASE_EPICS_CA_PORT}

        copy_to_stream_device ${2} $TOP
    popd
}
