#!/bin/sh
set -exu

DOCKER_REGISTRY=ghcr.io
DOCKER_USER_GROUP=lnls-sirius
DOCKER_IMAGE_PREFIX=${DOCKER_REGISTRY}/${DOCKER_USER_GROUP}

STREAM_BASE_IMAGE=${DOCKER_IMAGE_PREFIX}/streamdevice-ioc

AUTHOR="Claudio F. Carneiro <claudiofcarneiro@hotmail.com>"
BRANCH=$(git branch --no-color --show-current)
BUILD_DATE=$(date -I)
BUILD_DATE_RFC339=$(date --rfc-3339=seconds)
COMMIT=$(git rev-parse --short HEAD)
DATE=$(date -I)
DEPARTMENT=GAS
REPOSITORY=$(git remote show origin |grep Fetch|awk '{ print $3 }')

STREAM_BASE_TAG=stream-${DATE}

AGILENT4UHV_TAG=Agilent4UHV-${DATE}-${COMMIT}
COUNTINGPRU_TAG=CountingPRU-${DATE}-${COMMIT}
MBTEMP_TAG=MBTemp-${DATE}-${COMMIT}
MKS937B_TAG=MKS937b-${DATE}-${COMMIT}
RACKMON_TAG=RackMonitoring-${DATE}-${COMMIT}
SPIXCONV_TAG=SPIxCONV-${DATE}-${COMMIT}

cat << EOF > .env
# Generic
AUTHOR=${AUTHOR}
BRANCH=${BRANCH}
BUILD_DATE=${BUILD_DATE}
BUILD_DATE_RFC339=${BUILD_DATE_RFC339}
COMMIT_HASH=${COMMIT}
DATE=${DATE}
DEPARTMENT=${DEPARTMENT}

# Stream Device Image
STREAM_BASE_IMAGE=${STREAM_BASE_IMAGE}
STREAM_BASE_TAG=${STREAM_BASE_TAG}

# IOC
AGILENT4UHV_TAG=${AGILENT4UHV_TAG}
COUNTINGPRU_TAG=${COUNTINGPRU_TAG}
MBTEMP_TAG=${MBTEMP_TAG}
MKS937B_TAG=${MKS937B_TAG}
RACKMON_TAG=${RACKMON_TAG}
REPOSITORY=${REPOSITORY}
SPIXCONV_TAG=${SPIXCONV_TAG}
EOF
